//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EmpContactInfo
    {
        
        public long Id { get; set; }

        [RegularExpression("^\\w{0,50}$", ErrorMessage ="First Name Should not be greater than 50 Characters")]
        public string firstName { get; set; }

        [RegularExpression("^\\w{0,50}$", ErrorMessage = "Last Name Should not be greater than 50 Characters")]
        public string lastName { get; set; }

        [RegularExpression("^\\w{0,100}$", ErrorMessage = "Email Should be not greater than 100 Characters")]
        public string email { get; set; }

        [RegularExpression("^\\d{10,10}$", ErrorMessage = "Phone Number must be 10 digit number")]
        public string phoneNumber { get; set; }

        [RegularExpression("^\\w{0,8}$", ErrorMessage = "Status Should be not greater than 8 Characters")]
        public string status { get; set; }
    }
}
